"""
State
=====

Shared memory object passed between agents.
Stores interpreted data, clarifications, retrieved RAG results,
analysis, strategy, and various flags needed across the agent pipeline.
"""

from typing import Any, Dict, List, Optional


class State:
    """
    Shared state passed between agents.

    Attributes
    ----------
    input_text : str
        Raw user message.
    interpreted : dict or None
        Structured idea JSON created by InterpreterAgent.
    clarifications : list of str
        Questions generated by ClarifierAgent.
    rag_results : list of dict
        Retrieved Weaviate matches.
    analysis : str or None
        Mini-review output.
    strategy : str or None
        Strategist output (e.g., SWOT).
    is_new_idea : bool
        True if no existing matches in RAG.
    need_more_clarification : bool
        True if clarifier wants more user input.
    """

    def __init__(
        self,
        input_text: str = "",
        interpreted: Optional[Dict[str, Any]] = None,
        clarifications: Optional[List[str]] = None,
        rag_results: Optional[List[Dict[str, Any]]] = None,
        analysis: Optional[str] = None,
        strategy: Optional[str] = None,
        is_new_idea: bool = False,
        need_more_clarification: bool = False,
    ):
        self.input_text = input_text
        self.interpreted = interpreted
        self.clarifications = clarifications or []
        self.rag_results = rag_results or []
        self.analysis = analysis
        self.strategy = strategy
        self.is_new_idea = is_new_idea
        self.need_more_clarification = need_more_clarification
        self.mini_review = None
        self.summary = None

    def add_clarification(self, text: str) -> None:
        """
        Parameters
        ----------
        text : str
            Clarification question to add.
        """
        self.clarifications.append(text)

    def add_rag_results(self, results: List[Dict[str, Any]]) -> None:
        """
        Parameters
        ----------
        results : list of dict
            Retrieved entries from the vector database.
        """
        self.rag_results.extend(results)

    def merge(self, other: "State") -> None:
        """
        Parameters
        ----------
        other : State
            Another State object whose fields should be merged into this one.
        """
        if other.interpreted is not None:
            self.interpreted = other.interpreted

        if other.clarifications:
            self.clarifications.extend(other.clarifications)

        if other.rag_results:
            self.rag_results.extend(other.rag_results)

        if other.analysis is not None:
            self.analysis = other.analysis

        if other.strategy is not None:
            self.strategy = other.strategy

        if other.is_new_idea:
            self.is_new_idea = True

        if other.need_more_clarification:
            self.need_more_clarification = True

    def to_dict(self) -> Dict[str, Any]:
        """
        Returns
        -------
        dict
            Serializable representation of all public state fields.
        """
        return {
            "input_text": self.input_text,
            "interpreted": self.interpreted,
            "clarifications": list(self.clarifications),
            "rag_results": list(self.rag_results),
            "analysis": self.analysis,
            "strategy": self.strategy,
            "is_new_idea": self.is_new_idea,
            "need_more_clarification": self.need_more_clarification,
            "mini_review": self.mini_review,
            "summary": self.summary,
        }

    def reset(self) -> None:
        """
        Clears all agent-generated fields but preserves the original input text.
        """
        self.interpreted = None
        self.clarifications = []
        self.rag_results = []
        self.analysis = None
        self.strategy = None
        self.is_new_idea = False
        self.need_more_clarification = False
